### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'max_messages'

### ISSUE THREAD

**Issue by floringhimie** [rivethealth/mllp-http#9]
Traceback (most recent call last):
  File "/usr/local/bin/http2mllp", line 8, in <module>
    sys.exit(http2mllp())
  File "/usr/local/lib/python3.7/site-packages/mllp_http/main.py", line 102, in http2mllp
    max_messages=args.max_messages,
AttributeError: 'Namespace' object has no attribute 'max_messages'

Another error.

**Comment by floringhimie** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/http2mllp", line 8, in <module>
    sys.exit(http2mllp())
  File "/usr/local/lib/python3.7/site-packages/mllp_http/main.py", line 108, in http2mllp
    timeout=args.timeout / 100,
  File "/usr/local/lib/python3.7/site-packages/mllp_http/http2mllp.py", line 14, in __init__
    self.address = address
NameError: name 'address' is not defined

another one

**Comment by pauldraper** [comment]
Apologies. I evidently don't use http2mllp myself and have done a poor job testing this.
